/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum170625;

/**
 *
 * @author LABP2COMDOSEN
 */
public class MenuMinuman extends javax.swing.JFrame {

    private MenuUtama utama;
            
    public MenuMinuman() {
        initComponents();
    }
    
    public MenuMinuman(MenuUtama utama){
        this.utama =utama;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chkTehEs = new javax.swing.JCheckBox();
        chkLeci = new javax.swing.JCheckBox();
        chkEsBuah = new javax.swing.JCheckBox();
        chkTehJus = new javax.swing.JCheckBox();
        txtTehEs = new javax.swing.JTextField();
        txtLeci = new javax.swing.JTextField();
        txtEsBuah = new javax.swing.JTextField();
        txtTehJus = new javax.swing.JTextField();
        cbTehEs = new javax.swing.JComboBox<>();
        cbLeci = new javax.swing.JComboBox<>();
        cbEsBuah = new javax.swing.JComboBox<>();
        cbTehJus = new javax.swing.JComboBox<>();
        txtTotTehEs = new javax.swing.JTextField();
        txtTotLeci = new javax.swing.JTextField();
        txtTotEsBuah = new javax.swing.JTextField();
        txtTotTehJus = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Menu Minuman");

        chkTehEs.setText("Teh Es");
        chkTehEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTehEsActionPerformed(evt);
            }
        });

        chkLeci.setText("Leci");
        chkLeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLeciActionPerformed(evt);
            }
        });

        chkEsBuah.setText("Es Buah");
        chkEsBuah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsBuahActionPerformed(evt);
            }
        });

        chkTehJus.setText("Teh Jus");
        chkTehJus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTehJusActionPerformed(evt);
            }
        });

        cbTehEs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbTehEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTehEsActionPerformed(evt);
            }
        });

        cbLeci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbLeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLeciActionPerformed(evt);
            }
        });

        cbEsBuah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbEsBuah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEsBuahActionPerformed(evt);
            }
        });

        cbTehJus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbTehJus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTehJusActionPerformed(evt);
            }
        });

        txtTotTehEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotTehEsActionPerformed(evt);
            }
        });

        txtTotLeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotLeciActionPerformed(evt);
            }
        });

        txtTotEsBuah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotEsBuahActionPerformed(evt);
            }
        });

        btnProses.setText("Total");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali Ke Menu Utama");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkTehEs, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkLeci, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkEsBuah, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkTehJus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtTehJus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbTehJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(txtEsBuah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbEsBuah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(txtLeci, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbLeci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(txtTehEs, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(cbTehEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnProses)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtTotEsBuah, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addComponent(txtTotLeci)
                        .addComponent(txtTotTehEs))
                    .addComponent(txtTotTehJus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTehEs)
                    .addComponent(txtTehEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTehEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotTehEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkLeci)
                    .addComponent(txtLeci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLeci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotLeci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkEsBuah)
                    .addComponent(txtEsBuah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEsBuah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotEsBuah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTehJus)
                    .addComponent(txtTehJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTehJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotTehJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProses)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnKembali)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkLeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLeciActionPerformed
       txtLeci.setText("10000");
    }//GEN-LAST:event_chkLeciActionPerformed

    private void cbTehEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTehEsActionPerformed
         int jml = (int)cbTehEs.getSelectedIndex();
        double harga = Double.parseDouble(txtTehEs.getText());
        double total =jml*harga;
        txtTotTehEs.setText(Double.toString(total));
        
    }//GEN-LAST:event_cbTehEsActionPerformed

    private void txtTotTehEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotTehEsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotTehEsActionPerformed

    private void txtTotEsBuahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotEsBuahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotEsBuahActionPerformed

    private void chkTehEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTehEsActionPerformed
        txtTehEs.setText("5000");
    }//GEN-LAST:event_chkTehEsActionPerformed

    private void chkEsBuahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsBuahActionPerformed
       txtEsBuah.setText("8000");
    }//GEN-LAST:event_chkEsBuahActionPerformed

    private void chkTehJusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTehJusActionPerformed
        txtTehJus.setText("5000");
    }//GEN-LAST:event_chkTehJusActionPerformed

    private void txtTotLeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotLeciActionPerformed
        
    }//GEN-LAST:event_txtTotLeciActionPerformed

    private void cbLeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLeciActionPerformed
        int jml = (int)cbLeci.getSelectedIndex();
        double harga = Double.parseDouble(txtLeci.getText());
        double total =jml*harga;
        txtTotLeci.setText(Double.toString(total));
        
    }//GEN-LAST:event_cbLeciActionPerformed

    private void cbEsBuahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEsBuahActionPerformed
        int jml = (int)cbEsBuah.getSelectedIndex();
        double harga = Double.parseDouble(txtEsBuah.getText());
        double total =jml*harga;
        txtTotEsBuah.setText(Double.toString(total));
        
    }//GEN-LAST:event_cbEsBuahActionPerformed

    private void cbTehJusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTehJusActionPerformed
        int jml = (int)cbTehJus.getSelectedIndex();
        double harga = Double.parseDouble(txtTehJus.getText());
        double total =jml*harga;
        txtTotTehJus.setText(Double.toString(total));
        
    }//GEN-LAST:event_cbTehJusActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed

    double total = 0;

    try {
        if (chkTehEs.isSelected()) {
            double tehes = Double.parseDouble(txtTotTehEs.getText());
            total += tehes;
        }
    } catch (NumberFormatException e) {
        txtTotTehEs.setText("0");
    }

    try {
        if (chkLeci.isSelected()) {
            double leci = Double.parseDouble(txtTotLeci.getText());
            total += leci;
        }
    } catch (NumberFormatException e) {
        txtTotLeci.setText("0");
    }

    try {
        if (chkEsBuah.isSelected()) {
            double esbuah = Double.parseDouble(txtTotEsBuah.getText());
            total += esbuah;
        }
    } catch (NumberFormatException e) {
        txtTotEsBuah.setText("0");
    }

    try {
        if (chkTehJus.isSelected()) {
            double tehjus = Double.parseDouble(txtTotTehJus.getText());
            total += tehjus;
        }
    } catch (NumberFormatException e) {
        txtTotTehJus.setText("0");
    }

    txtTotal.setText(String.valueOf(total));


    }//GEN-LAST:event_btnProsesActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
      String total = txtTotal.getText();
        if(utama != null) {
                 utama.setTotalMinuman(total);
                 utama.setVisible(true);
        }
        this.dispose(); // menutup jendela form menu minuman
        
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMinuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnProses;
    private javax.swing.JComboBox<String> cbEsBuah;
    private javax.swing.JComboBox<String> cbLeci;
    private javax.swing.JComboBox<String> cbTehEs;
    private javax.swing.JComboBox<String> cbTehJus;
    private javax.swing.JCheckBox chkEsBuah;
    private javax.swing.JCheckBox chkLeci;
    private javax.swing.JCheckBox chkTehEs;
    private javax.swing.JCheckBox chkTehJus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEsBuah;
    private javax.swing.JTextField txtLeci;
    private javax.swing.JTextField txtTehEs;
    private javax.swing.JTextField txtTehJus;
    private javax.swing.JTextField txtTotEsBuah;
    private javax.swing.JTextField txtTotLeci;
    private javax.swing.JTextField txtTotTehEs;
    private javax.swing.JTextField txtTotTehJus;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
